Map<String, int> depoFormList = {
  "Manav sevkiyatları saatinde\nçıkarıldı mı?":0,
  "Bozuk ürün kontrolü yapıldı mı?":0,
  "SB çıkışları ile mal kabul kontrol\nedildi mi?":0,
  "Sivas birlik faturası kontrol edilip\nimzalandı mı?":0,
  "Ana kalem ürünlerinin sipariş\nkarşılamasına bakıldı mı?":0,
  "Sipariş ve sevk tonajları kontrol\nedildi mi?":0,
  "Manav depo stoğu kontrol\nedildi mi?":0,
  "Kalan ürün dönüşümü sağlandı mı?":0,
  "Kasa alanı kontrol edildi mi?":0,
  "Depo çalışanlarının giriş ve çıkış\nsaatleri kontrol edildi mi?":0
};

Map<String, int> shopFormList = {
  "Manav düzeni sağlanmış mı?":0,
  "Manav fifosu yapılmış mı? Ürünler\nayıklanmış mı?":0,
  "Manav düzeni dizilime uygun mu?":0,
  "Aktif ürünler mağazada mevcut mu?":0,
  "Halk günü teşhirleri ve haftanın ürünleri\nteşhire açılmış mı":0,
  "Halk günü teşhirlerine ve haftanın\nürünlerine afiş yazılmış mı?":0,
  "Künyeler güncel mi?":0,
  "Fiyat değişikliği yapılmış mı?":0,
  "Mağazanın etiket ve görselleri düzgün\nmü? KG-Adet ibaresi var mı?":0,
  "Çıkma bölümü temiz ve düzenlı mi?":0,
  "Kuruyemiş standı düzenli mi? Ürünler\nmevcut mu?":0,
  "Kasa terazileri doğru tartım yapıyor mu?":0,
  "Manav baskülü depoda mı?":0,
  "Mağazanın deposundaki manav stoğu\nyeterli mi? Eksik fazla mevcut mu?":0,
  "Mağaza manav kasaları teşhirde\nkullanılıyor mu?":0,
  "Mağazanın deposundaki kasa alanı\ndüzenli mi? Doğru çıkış yapılıyor mu?":0,
  "Mağaza doğru sipariş veriyor mu?":0,
  "Mağazada aktif ürün dışında hatalı koddan\nsatış yapışıyor mu?":0,
  "Manav ürünleri çekleniyor mu?":0,
  "Manav personeli saatinde giriş-çıkış\nyapıyor mu?":0,
  "Mağaza düzenli olarak fire çıkışı\nyapıyor mu?":0,
  "Manav ciro, ciro payı ve tonaj büyümeleri\nmağaza ile paylaşıldı mı?":0,
  "Manav personeli saç-sakal ve kılık-kiyafeti\ntemiz ve düzenli mi?":0,
};