Map<String, int> inShopOpeningCheckingList = {
  "Günlük evraklar işlenmiş mi?":0,
  "Kasiyer Defteri verileri işlenmiş mi?":0,
  "SKT kontrolü yapılmış mı?":0,
  "Kasa altı poşetler yeterli mi?":0,
  "Kasa altı çöpler dökülmüş mü?":0,
  "Ofis ve depo kapıları kilitli mi?":0,
  "Kasa çekmeceleri açık mı?":0,
  "Kasa altı ve etrafında resmi evrak var mı?":0,
  "WC ve lavabo muslukları kapalı mı?":0,
  "Kasalar temizlenmiş mi?":0,
  "Mağaza anahtarları ilgili sorumluda mı?":0,
  "Mutfak- lavabo temizliği yapılmış mı?":0,
  "Mağaza düzeni sabah satış için hazır mı?":0,
  "Ofis ve depo çöpleri dökülmüş mü?":0,
  "Prizlerde takılı herhangi bir cihaz var mı?":0,
  "Kameralar kayıt yapıyor mu?":0,
  "Zemin temizliği doğru yapılmış mı?":0,
  "Kasa etrafı düzenlenmiş mi?":0,
  "Manav düzeni sabah satış için hazır mı?":0,
  "Kasa altı poşetler hazırlanmış mı?":0,
  "Isıtıcı ve klimalar kapalı mı?":0
};

Map<String, int> outShopOpeningCheckingList = {
  "Alarm kurularak mağazaya giriş yapılıyor mu? aasda asdsadasd asdasdasd":0,
  "Mağaza yeterli personel ile açıldı mı?":0,
  "Mağaza açılışından önce uygun zamanda gelindi mi?":0,
  "Giriş-çıkış kapısı, kepenkler ve depo kapısı kapalı mı?":0,
  "Mağaza anahtarları ilgili sorumluda mı?":0,
};

Map<String, int> inShopClosingCheckingList = {
  "Prizlere takılı herhangi bir cihaz var mı?":0,
  "Dolap aydınlatmaları ve perdeler kapalı mı?":0,
  "Kameralar kayıt yapıyor mu?":0,
  "Mutfak, lavabo temizliği yapılmış mı?":0,
  "Kasa çekmeceleri açık mı?":0,
  "Kasa altı poşetleri hazırlanmış mı ve yeterli mi?":0,
  "Kasa etrafı düzenlenmiş mi?":0,
  "Mağaza düzeni satış için hazır mı?":0,
  "Wc ve lavabo muslukları kapalı mı?":0,
  "Günlük evraklar işlenmiş mi?":0,
  "Zemin temizliği doğru yapılmış mı?":0,
  "Ofis ve depo kapıları kilitli mi?":0,
  "Isıtıcı ve klimalar kapalı mı?":0,
  "Ofis ve depo çöpleri dökülmüş mü?":0,
  "Kasa altı ve etrafında resmi evrak var mı?":0,
  "Kasalar temizlenmiş mi?":0,
  "Kasiyer defteri verileri işlenmiş mi?":0,
  "SKT kontrolü yapılmış mı?":0,
  "Manav düzeni satış için hazır mı?":0,
  "Kasa altı çöpler dökülmüş mü?":0,
};

Map<String, int> outShopClosingCheckingList = {
  "Mağazada zamanında karartma yapılıyor mu?":0,
  "Zeminin temizliği yapılıyor mu?":0,
  "Alarm kurularak çıkılıyor mu?":0,
  "Dolap aydınlatmaları ve perdeler kapatıldı mı?":0,
  "Çalışanlar mağazayı aynı anda mı terk ediyor?":0,
  "Giriş kapısı ve kepenkler zamanında kapatılıyor mu?":0,
  "Son müşteri çıkışına eşlik ediliyor mu?":0,
  "Kasa çıkışları zamanında sorumlu eşliğinde alınıyor mu?":0,
};